# A workflow to build `gOSWI` using GitHub Actions.

# Note the extra complexity to make sure this compiles with Cgo,
# meaning that we need to install the ImageMagick 7 C/C++ development libraries & headers
# ... which, in turn, means getting the packages from Debian, since Ubuntu doesn't
#     have the latest versions; they're still stuck with ImageMagick 6.9, as of late 2024,
#     (Ubuntu 24.04).

# This is getting impossible to keep up with; we're switching to compiling everything and
# see how it goes. Soon, oh, soon we'll just fork/spawn a `magick` process and no more
# compilation will be required... (gwyneth 20251023)

name: 'gOSWI built with compiled ImageMagick 7'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Note: Ubuntu doesn't like ImageMagick 7, we'll compile everything instead
    - name: Install packages needed for compilation
      # Need more packages? Just add their names below!
      #
      run: |
        sudo apt-get update
        sudo apt-get install -y wget autoconf pkg-config build-essential curl libbz2-dev libfontconfig-dev libfreetype-dev libgs-dev libgvc6 libjpeg-dev libpng-dev libtiff-dev libxml2-dev

    - name: Download ImageMagick source files to /tmp
      run: |
        cd /tmp
        wget https://github.com/ImageMagick/ImageMagick/archive/refs/tags/7.1.2-7.tar.gz
        tar xvzf 7.1.2-7.tar.gz
        rm 7.1.2-7.tar.gz

    - name: Configure the ImageMagick build
      run: |
        cd /tmp/ImageMagick-7.1.2-7
        sh ./configure --prefix=/usr/local --with-bzlib=yes --with-fontconfig=yes --with-freetype=yes --with-gslib=yes --with-gvc=yes --with-jpeg=yes --with-jp2=yes --with-png=yes --with-tiff=yes --with-xml=yes --with-gs-font-dir=yes

    - name: Compile ImageMagick
      run:
        cd /tmp/ImageMagick-7.1.2-7
        make -j

    - name: Install ImageMagick
      # For the sake of completude, we'll also add the required included shared libraries on the path
      # for dynamically linked binaries via `ld.so`. This may not be necessary for Go, but who knows...
      # (gwyneth 20251023)
      run: |
        cd /tmp/ImageMagick-7.1.2-7
        sudo make install
        sudo echo "/usr/local/lib/ImageMagick-7.1.2/modules-Q16HDRI/filters" > /etc/ld.so.conf.d/ImageMagick.conf
        sudo ldconfig /usr/local/lib/

    - name: Just check if ImageMagick was built successfully
      # Bote: this is just for debugging the compilation, to make sure it's all fine
      run: $(which identify) -list configure

    # Moving on to Go...
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
#        go-version: '1.24'
        go-version-file: './go.mod'

    # Make sure that Cgo is enabled
    - name: Build
      run:  CGO_CFLAGS_ALLOW='-Xpreprocessor' go build -v ./...

# Tests haven't been done yet.
#    - name: Test
#      run: go test -v ./...
